CUSTOM_TESTING_SENTENCES = [
        # puns
        "Why don't scientists trust atoms? Because they make up everything.",
        "Why did the scarecrow win an award? Because he was outstanding in his field.",
        "I used to be a baker, but I couldn't make enough dough.",
        "I don't trust stairs. They're always up to something.",
        "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
        "Why are skeletons so calm? Because nothing gets under their skin.",
        "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
        "I stayed up all night to see where the sun went. Then it dawned on me.",
        "The lumberjack loved his new computer. He especially liked logging in.",
        "A ghost walked into a bar and ordered a spirit.",
        "I wondered why the frisbee was getting bigger. Then it hit me.",
        "What do you get from a pampered cow? Spoiled milk.",
        "The invention of the shovel was groundbreaking.",
        "I'm trying to learn to handle my fear of elevators. I'm taking steps to avoid them.",
        "I'm reading a horror story in Braille. Something bad is about to happen, I can feel it.",
        "A bee's hair is always sticky because it uses a honeycomb.",
        "What do you call a pig that does karate? A pork chop.",
        "Why are fish so smart? Because they live in schools.",
        "My sea sickness comes in waves.",
        "I'm glad I know sign language, it's pretty handy.",
        "I'm terrified of clocks. They're very alarming.",
        "I told my computer I needed a break, and it said, 'No problem, I'm already in bits.'",
        "A midget psychic escaped from prison. He was a small medium at large.",
        "Why did the coffee file a police report? It got mugged.",
        "I asked the AI for a joke, and it responded so promptly.",
        "That must be a loud musician. He's got a lot of amps.",
        "The calendar maker's days are numbered.",
        "Why did the biologist break up with the physicist? They had no chemistry.",
        "I asked a sign painter for a good pun. He gave me a sign.",
        "The life of a lighthouse keeper is very isolated, but they're always in the spotlight.",
        "The optometrist fell into his lens-grinding machine and made a spectacle of himself.",
        "A police officer ticketed me for my fantastic driving. He said, 'It's a fine.'",
        "I wasn't originally going to get a brain transplant, but then I changed my mind.",
        "He was a carpenter, but he was fired. He just wasn't nailing it.",
        "The magician was walking down the street and turned into a drugstore.",
        "The soldier who survived mustard gas and pepper spray is now a seasoned veteran.",
        "My girlfriend said she was leaving me because I'm obsessed with baseball. I told her she was way off base.",
        "He had a photographic memory, but it was never developed.",
        "I used to be a historian, but I realized there was no future in it.",
        "A prisoner's favorite punctuation mark is a period. It marks the end of his sentence.",
        "The duck told the waiter to put the drink on his bill.",
        "I'm thinking of becoming a pilot. My career would really take off.",
        "The man who survived a fall from a 10-story building was not worried. He was just a little shaken.",
        "Why was the math book sad? It had too many problems.",
        "The past, the present, and the future walked into a bar. It was tense.",
        "The geography teacher was fired for getting lost. He couldn't find his bearings.",
        "What's the difference between a zookeeper and a gambler? One has a stake in the lions, the other has lions at stake.",
        "Why are musicians so bad at fishing? They're always dropping the bass.",
        "I tried to sue the airline for losing my luggage. I lost my case.",
        "The tailor was fired from his job. It seems he just wasn't suited for the work.",

        # non-puns
        # "The train is scheduled to arrive at 5:00 PM.",
        # "My favorite color is blue, but I also like green.",
        # "I need to buy groceries after work.",
        # "The library is closed on Sundays.",
        # "This new software update has several security patches.",
        # "The Earth revolves around the Sun in approximately 365 days.",
        # "I am planning to visit my family next month.",
        # "The dog barked at the mail carrier.",
        # "This book provides a detailed history of the Roman Empire.",
        # "She is learning to play the piano.",
        # "The meeting was postponed due to a scheduling conflict.",
        # "Remember to charge your phone before you leave.",
        # "The recipe requires two cups of flour and one cup of sugar.",
        # "Mount Everest is the tallest mountain in the world.",
        # "He wore a heavy coat because it was cold outside.",
        # "The children are playing in the park.",
        # "I prefer to drink coffee in the morning.",
        # "The car's engine is making a strange noise.",
        # "We watched a documentary about penguins last night.",
        # "The final exam will cover all chapters from the textbook.",
        # "The sky is very clear tonight, so we can see the stars.",
        # "My computer is running slowly; I should probably restart it.",
        # "The restaurant's special of the day is grilled salmon.",
        # "She forgot her umbrella and got wet in the rain.",

        "Actions speak louder than words.",
        "The early bird catches the worm.",
        "A stitch in time saves nine.",
        "Don't count your chickens before they hatch.",
        "A watched pot never boils.",
        "The grass is always greener on the other side.",
        "Don't put all your eggs in one basket.",
        "Every cloud has a silver lining.",
        "A bird in the hand is worth two in the bush.",
        "Better late than never.",
        "Birds of a feather flock together.",
        "Haste makes waste.",
        "Curiosity killed the cat.",
        "Don't judge a book by its cover.",
        "If it ain't broke, don't fix it.",
        "Practice makes perfect.",
        "An apple a day keeps the doctor away.",
        "Absence makes the heart grow fonder.",
        "It's raining cats and dogs.",
        "He let the cat out of the bag.",
        "She spilled the beans.",
        "You have to bite the bullet.",
        "He hit the nail on the head.",
        "That's the best of both worlds.",
        "Don't cry over spilled milk.",
        "The presentation will begin in ten minutes.",
        "Many people commute to the city for work.",
        "The museum's new exhibit features modern art.",
        "He is studying to become a mechanical engineer.",
        "The traffic was heavy on the highway this morning.",
        "I have a dentist appointment on Friday.",
        "The new policy will take effect on the first of the month.",
        "I am going to the gym.",
        "The company reported its quarterly earnings today.",
        "She is painting the walls of her living room.",
        "The store will close at 9:00 PM tonight.",
        "I need to get my car's oil changed soon.",
        "The national park is home to many different species of wildlife.",
        "He is allergic to peanuts.",
        "The flight was delayed for two hours.",
        "The package should be delivered by tomorrow afternoon.",
        "I finished reading the novel yesterday.",
        "The project deadline is next Wednesday.",
        "The wind is blowing strongly from the west.",
        "She is training for a marathon.",
        "The phone's battery is almost dead.",
        "The baby is sleeping in his crib.",
        "The monkeys are at home",
        "The government announced new environmental regulations.",
        "He is taking a course on statistics and data analysis."
    ]